### ISSUE TITLE
Finder Action "Create Searchable PDF" creates trial watermark

### ISSUE THREAD

**Issue by zorae** [holtwick/pdfify#77]
When running the Finder Action "Create Searchable PDF", the resulting file contains a "https://pdfify.app/trial" watermark. This is unexpected, as I am running the Mac App Store version of PDFify with Pro features activated.

App Version Info:
de.holtwick.mac.PDFify@3.4+153 TS0PF3VD650QZFPF9R17GRV1Q4

**Comment by holtwick** [comment]
Indeed, this should not happen. Thanks for the bug report. I'll fix ASAP.

**Comment by holtwick** [comment]
@zorae could you please try the following:

1. Start the main app once. Check if you have a valid license by looking at the last tab of the settings.
2. Try again to "Create Searchable PDF"

Due to technical reasons, the main app has to be started once before the license applies to the extensions. 

If you still encounter problems, you could send log files via the support dialog. Therefore, go to main menu "Help" > "Support" and then press + in the dialog and choose "Log files". Thanks.

**Comment by zorae** [comment]
@holtwick indeed, issue is resolved after opening the main app! Closing this issue, since you apparently can't prevent this quirk.

**Comment by holtwick** [comment]
@zorae thanks for the feedback. Indeed, I put some hours into it and no chance to do it "the right way" due to limitations in Apple's API.
